// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  LBoard_All_Time = "LBoard_All_Time",
  LBoard_Weekly = "LBoard_Weekly",
  MAIN_POSITION = "MAIN_POSITION",
  PINES = "PINES",
  Prizes = "Prizes",
  camp_gltf = "camp.gltf",
  env_rocks = "env_rocks",
  loc = "loc",
  pine_gltf = "pine.gltf",
  pine_gltf_10 = "pine.gltf_10",
  pine_gltf_11 = "pine.gltf_11",
  pine_gltf_12 = "pine.gltf_12",
  pine_gltf_13 = "pine.gltf_13",
  pine_gltf_14 = "pine.gltf_14",
  pine_gltf_15 = "pine.gltf_15",
  pine_gltf_16 = "pine.gltf_16",
  pine_gltf_17 = "pine.gltf_17",
  pine_gltf_18 = "pine.gltf_18",
  pine_gltf_19 = "pine.gltf_19",
  pine_gltf_2 = "pine.gltf_2",
  pine_gltf_20 = "pine.gltf_20",
  pine_gltf_21 = "pine.gltf_21",
  pine_gltf_22 = "pine.gltf_22",
  pine_gltf_23 = "pine.gltf_23",
  pine_gltf_24 = "pine.gltf_24",
  pine_gltf_25 = "pine.gltf_25",
  pine_gltf_26 = "pine.gltf_26",
  pine_gltf_27 = "pine.gltf_27",
  pine_gltf_28 = "pine.gltf_28",
  pine_gltf_29 = "pine.gltf_29",
  pine_gltf_3 = "pine.gltf_3",
  pine_gltf_30 = "pine.gltf_30",
  pine_gltf_31 = "pine.gltf_31",
  pine_gltf_5 = "pine.gltf_5",
  pine_gltf_6 = "pine.gltf_6",
  pine_gltf_7 = "pine.gltf_7",
  pine_gltf_8 = "pine.gltf_8",
  pine_gltf_9 = "pine.gltf_9",
  prize_1 = "prize_1",
  prize_10 = "prize_10",
  prize_11 = "prize_11",
  prize_12 = "prize_12",
  prize_2 = "prize_2",
  prize_3 = "prize_3",
  prize_4 = "prize_4",
  prize_5 = "prize_5",
  prize_6 = "prize_6",
  prize_7 = "prize_7",
  prize_8 = "prize_8",
  prize_9 = "prize_9",
} 
